/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyAccountRouteImport } from './routes/auth/verify-account'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedDashboardProductsIndexRouteImport } from './routes/_authenticated/dashboard/products/index'
import { Route as AuthenticatedDashboardProductsTrainingIdIndexRouteImport } from './routes/_authenticated/dashboard/products/$trainingId/index'

const AuthenticatedDashboardIndexLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/',
)()
const AuthenticatedDashboardUsersLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/users',
)()
const AuthenticatedDashboardSettingsLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/settings',
)()
const AuthenticatedDashboardProfileLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/profile',
)()
const AuthenticatedDashboardNotificationsLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/notifications',
)()

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyAccountRoute = AuthVerifyAccountRouteImport.update({
  id: '/verify-account',
  path: '/verify-account',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexLazyRoute =
  AuthenticatedDashboardIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/index.lazy').then((d) => d.Route),
  )
const AuthenticatedDashboardUsersLazyRoute =
  AuthenticatedDashboardUsersLazyRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/users.lazy').then((d) => d.Route),
  )
const AuthenticatedDashboardSettingsLazyRoute =
  AuthenticatedDashboardSettingsLazyRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/settings.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardProfileLazyRoute =
  AuthenticatedDashboardProfileLazyRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/profile.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardNotificationsLazyRoute =
  AuthenticatedDashboardNotificationsLazyRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/notifications.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardProductsIndexRoute =
  AuthenticatedDashboardProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardProductsTrainingIdIndexRoute =
  AuthenticatedDashboardProductsTrainingIdIndexRouteImport.update({
    id: '/products/$trainingId/',
    path: '/products/$trainingId/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-account': typeof AuthVerifyAccountRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsLazyRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileLazyRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsLazyRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersLazyRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexLazyRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsIndexRoute
  '/dashboard/products/$trainingId': typeof AuthenticatedDashboardProductsTrainingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-account': typeof AuthVerifyAccountRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsLazyRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileLazyRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsLazyRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersLazyRoute
  '/dashboard': typeof AuthenticatedDashboardIndexLazyRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsIndexRoute
  '/dashboard/products/$trainingId': typeof AuthenticatedDashboardProductsTrainingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-account': typeof AuthVerifyAccountRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsLazyRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileLazyRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsLazyRoute
  '/_authenticated/dashboard/users': typeof AuthenticatedDashboardUsersLazyRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexLazyRoute
  '/_authenticated/dashboard/products/': typeof AuthenticatedDashboardProductsIndexRoute
  '/_authenticated/dashboard/products/$trainingId/': typeof AuthenticatedDashboardProductsTrainingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/verify-account'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/products'
    | '/dashboard/products/$trainingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/verify-account'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/products'
    | '/dashboard/products/$trainingId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/verify-account'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/users'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/products/'
    | '/_authenticated/dashboard/products/$trainingId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-account': {
      id: '/auth/verify-account'
      path: '/verify-account'
      fullPath: '/auth/verify-account'
      preLoaderRoute: typeof AuthVerifyAccountRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/users': {
      id: '/_authenticated/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthenticatedDashboardUsersLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/products/': {
      id: '/_authenticated/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof AuthenticatedDashboardProductsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/products/$trainingId/': {
      id: '/_authenticated/dashboard/products/$trainingId/'
      path: '/products/$trainingId'
      fullPath: '/dashboard/products/$trainingId'
      preLoaderRoute: typeof AuthenticatedDashboardProductsTrainingIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyAccountRoute: typeof AuthVerifyAccountRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyAccountRoute: AuthVerifyAccountRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardNotificationsLazyRoute: typeof AuthenticatedDashboardNotificationsLazyRoute
  AuthenticatedDashboardProfileLazyRoute: typeof AuthenticatedDashboardProfileLazyRoute
  AuthenticatedDashboardSettingsLazyRoute: typeof AuthenticatedDashboardSettingsLazyRoute
  AuthenticatedDashboardUsersLazyRoute: typeof AuthenticatedDashboardUsersLazyRoute
  AuthenticatedDashboardIndexLazyRoute: typeof AuthenticatedDashboardIndexLazyRoute
  AuthenticatedDashboardProductsIndexRoute: typeof AuthenticatedDashboardProductsIndexRoute
  AuthenticatedDashboardProductsTrainingIdIndexRoute: typeof AuthenticatedDashboardProductsTrainingIdIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardNotificationsLazyRoute:
      AuthenticatedDashboardNotificationsLazyRoute,
    AuthenticatedDashboardProfileLazyRoute:
      AuthenticatedDashboardProfileLazyRoute,
    AuthenticatedDashboardSettingsLazyRoute:
      AuthenticatedDashboardSettingsLazyRoute,
    AuthenticatedDashboardUsersLazyRoute: AuthenticatedDashboardUsersLazyRoute,
    AuthenticatedDashboardIndexLazyRoute: AuthenticatedDashboardIndexLazyRoute,
    AuthenticatedDashboardProductsIndexRoute:
      AuthenticatedDashboardProductsIndexRoute,
    AuthenticatedDashboardProductsTrainingIdIndexRoute:
      AuthenticatedDashboardProductsTrainingIdIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
